# -*- coding: utf-8 -*-
# Copyright 2016 Sunflower IT <http://sunflowerweb.nl>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import models, fields, api, _
from odoo.exceptions import ValidationError


class AnalyticLine(models.Model):
    """Restrict edit and delete on analytic lines generated by holidays"""
    _inherit = 'account.analytic.line'

    leave_id = fields.Many2one(comodel_name='hr.holidays', string='Leave id')

    @api.depends('date', 'user_id', 'project_id', 'sheet_id_computed.date_to',
                 'sheet_id_computed.date_from',
                 'sheet_id_computed.employee_id',
                 'account_id.is_leave_account')
    def _compute_sheet(self):
        """Links the timesheet line to the corresponding sheet
        """
        for ts_line in self:
            if not ts_line.account_id.is_leave_account:
                super(AnalyticLine, ts_line)._compute_sheet()
            else:
                sheets = self.env['hr_timesheet_sheet.sheet'].search(
                    [('date_to', '>=', ts_line.date),
                     ('date_from', '<=', ts_line.date),
                     ('employee_id.user_id.id', '=', ts_line.user_id.id),
                     ('state', 'in', ['draft', 'new'])])
                if sheets:
                    ts_line.sheet_id_computed = sheets[0]
                    ts_line.sheet_id = sheets[0]

    def create(self, vals):
        # if the analytic line is for a project on leave and there is
        # a leave on the same day, then link the line to the leave
        if vals.get("project_id", False) and vals.get("sheet_id", False) and vals.get("date", False) and not vals.get("leave_id", False):
            project_id = vals.get("project_id", False)
            date = vals.get("date")
            sheet_id =  vals.get("sheet_id")
            project = self.env["project.project"].browse(project_id)
            account = project.analytic_account_id
            existing_line = self.env["account.analytic.line"].search([("date", "=", date), ("account_id", "=", account.id), ("sheet_id", "=", sheet_id)], limit = 1)
            if existing_line.leave_id:
                vals.update({"leave_id": existing_line.leave_id.id})
        return super(AnalyticLine, self).create(vals)
